version: '3'

networks:
  default:
    external:
      name: cestao

services:
  backend:
    build: .
    ports:
      - "8080:8080"
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123"
    ports:
      - "15432:5432"
    volumes:
      - $HOME/docker/volumes/postgresql:/var/lib/postgresql/data 

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "teste@teste.com"
      PGADMIN_DEFAULT_PASSWORD: "123"
    ports:
      - "16543:80"
    depends_on:
      - postgres