version: '3'

networks:
  default:
    external:
      name: cestao

services:
  backend:
    build: .
    ports: 
      - '8080:8080'
    environment:
      POSTGRES_HOST: 'cestao_postgres'
      POSTGRES_USER: 'cestao'
      POSTGRES_PASSWORD: '123'
      POSTGRES_DB: 'cestaodb'
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: cestao_postgres
    environment:
      POSTGRES_USER: 'cestao'
      POSTGRES_PASSWORD: '123'
      POSTGRES_DB: 'cestaodb'
    ports:
      - '15432:5432'

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'teste@teste.com'
      PGADMIN_DEFAULT_PASSWORD: '123'
    ports:
      - '16543:80'
    depends_on:
      - postgres